### ISSUE TITLE
Failed to boot

### ISSUE THREAD

**Issue by EraserCN** [revunix/ThinkCentre-M710Q#1]
Failed to boot MacOS 12.6 on my device, the screen just went black after choosing to boot Install MacOS.

**Comment by Theoldshark** [comment]
Strange. My ThinkCentre boots 12.6.1 (21G217).

**Comment by revunix** [comment]
> Strange. My ThinkCentre boots 12.6.1 (21G217).

This is because not everyone uses the same CPU/iGPU. 


> Failed to boot MacOS 12.6 on my device, the screen just went black after choosing to boot Install MacOS.

Boot with -v and show us the log.

**Comment by Theoldshark** [comment]
> > Strange. My ThinkCentre boots 12.6.1 (21G217).
> 
> This is because not everyone uses the same CPU/iGPU.
> 
> > Failed to boot MacOS 12.6 on my device, the screen just went black after choosing to boot Install MacOS.
> 
> Boot with -v and show us the log.

Right. I should mention I updated OC to release 0.8.5 and I updated kexts as well.

**Comment by revunix** [comment]
> Right. I should mention I updated OC to release 0.8.5 and I updated kexts as well.

Maybe you can upload your updated config for him here in this issue.

**Comment by EraserCN** [comment]
I've created a model EFI based on your work. Mine unrooted probably due to it's i5-7500T

https://github.com/EraserCN/Lenovo-m710q-Hackintosh-EFI

**Comment by Theoldshark** [comment]
> > Right. I should mention I updated OC to release 0.8.5 and I updated kexts as well.
> 
> Maybe you can upload your updated config for him here in this issue.

Yes, I already intended to do that. There are still minor bugs in config, but it works ...

**Comment by Theoldshark** [comment]
https://github.com/Theoldshark/EFI-Lenovo-M710q
